name: MLflow CI Training & Docker

on:
  push:
    paths:
      - MLProject/**

jobs:
  train-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.7'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install \
            mlflow==2.19.0 \
            scikit-learn \
            pandas \
            numpy \
            matplotlib

      - name: Run MLflow Project (Training)
        run: |
          cd MLProject
          mlflow run . --env-manager=local 2>&1 | tee mlflow_output.log
          echo "TRAINING DONE"
          
          RUN_ID=$(grep -oP "Run ID: \K[a-f0-9]+" mlflow_output.log | tail -1)
          if [ -z "$RUN_ID" ]; then
            RUN_ID=$(ls -td mlruns/*/* | head -n 1 | awk -F'/' '{print $(NF)}')
          fi
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Detected RUN_ID=$RUN_ID"

      - name: Debug - List mlruns
        run: |
          cd MLProject
          find mlruns -type f -name "meta.yaml" | head -5
          if [ -f mlruns_output.log ]; then cat mlruns_output.log; fi

      - name: Docker Login
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login \
            docker.io \
            -u "${{ secrets.DOCKER_USERNAME }}" \
            --password-stdin

      - name: Build Docker Image with MLflow
        env:
          MLFLOW_RUN_ID: ${{ env.RUN_ID }}
        run: |
          cd MLProject
          
          echo "Using MLFLOW_RUN_ID=$MLFLOW_RUN_ID"
          
          if [ -z "$MLFLOW_RUN_ID" ]; then
            echo "ERROR: MLFLOW_RUN_ID is empty!"
            exit 1
          fi
          
          mlflow models build-docker \
            -m "runs:/$MLFLOW_RUN_ID/model" \
            -n "rizkye99/eafc26-model:${{ github.run_id }}"

      - name: Push Docker Image to Docker Hub
        run: |
          docker push "rizkye99/eafc26-model:${{ github.run_id }}"
          docker tag "rizkye99/eafc26-model:${{ github.run_id }}" rizkye99/eafc26-model:latest
          docker push rizkye99/eafc26-model:latest
