name: MLflow CI Training & Docker

on:
  push:
    paths:
      - MLProject/**

jobs:
  train-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.7'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install \
            mlflow==2.19.0 \
            scikit-learn \
            pandas \
            numpy \
            matplotlib

      - name: Run MLflow Project (Training)
        run: |
          cd MLProject
          mlflow run . --env-manager=local
          echo "TRAINING DONE"

      - name: Get latest RUN_ID
        run: |
          cd MLProject
          RUN_ID=$(ls -td mlruns/*/* | head -n 1 | awk -F'/' '{print $(NF)}')
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Detected RUN_ID=$RUN_ID"

      - name: Docker Login
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login \
            -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image with MLflow
        run: |
          cd MLProject
      
          echo "MLFLOW_RUN_ID=$MLFLOW_RUN_ID"
      
          mlflow models build-docker \
            -m runs:/$MLFLOW_RUN_ID/model \
            -n rizkye99/eafc26-model


      - name: Push Docker Image to Docker Hub
        run: |
          docker push rizkye99/eafc26-model
